---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: debug
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@c21017a4a2fc9f42953bcc907e375a5a544557ec # v41.0.18
        with:
          configurationFile: .github/renovate.json
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"