name: Wakatime Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: true
          SHOW_LINES_OF_CODE: false
          SHOW_PROFILE_VIEWS: false
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_UPDATED_DATE: false
          SHOW_LANGUAGE_PER_REPO: false
          COMMIT_MESSAGE: "Automated Coding Activity Update :rocket:"